// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx29FFc87fkRRwn8e1pLO0QL2rwhPJc5k',
    appId: '1:547759994729:web:15feab2f91b2635b98aff8',
    messagingSenderId: '547759994729',
    projectId: 'autocare-app-38a2a',
    authDomain: 'autocare-app-38a2a.firebaseapp.com',
    storageBucket: 'autocare-app-38a2a.firebasestorage.app',
    measurementId: 'G-Y2VY4N891B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA66oKA_lNPDlhpPyElps6OYaWhKol1-tk',
    appId: '1:547759994729:android:b77cd3c55b2e23df98aff8',
    messagingSenderId: '547759994729',
    projectId: 'autocare-app-38a2a',
    storageBucket: 'autocare-app-38a2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJnb7e4FVLT39Y4xneX-Ibd652Y57o_1w',
    appId: '1:547759994729:ios:60ff83b924c1c9b698aff8',
    messagingSenderId: '547759994729',
    projectId: 'autocare-app-38a2a',
    storageBucket: 'autocare-app-38a2a.firebasestorage.app',
    iosBundleId: 'com.example.autocareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJnb7e4FVLT39Y4xneX-Ibd652Y57o_1w',
    appId: '1:547759994729:ios:60ff83b924c1c9b698aff8',
    messagingSenderId: '547759994729',
    projectId: 'autocare-app-38a2a',
    storageBucket: 'autocare-app-38a2a.firebasestorage.app',
    iosBundleId: 'com.example.autocareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx29FFc87fkRRwn8e1pLO0QL2rwhPJc5k',
    appId: '1:547759994729:web:e304e574e40c4b4398aff8',
    messagingSenderId: '547759994729',
    projectId: 'autocare-app-38a2a',
    authDomain: 'autocare-app-38a2a.firebaseapp.com',
    storageBucket: 'autocare-app-38a2a.firebasestorage.app',
    measurementId: 'G-089V6X0DVE',
  );
}
